export const testUsers = [
  {
    email: "dev+admin@joindaquest.io",
    username: "admin",
    password: "Testpass123@",
    referralCode: "ADMIN1",
    role: "admin",
    referredBy: "None",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+amaka-obi@joindaquest.io",
    username: "amakaobi",
    password: "Testpass123@",
    referralCode: "AMAKA1",
    role: "kol",
    referredBy: "None",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+liam-oconnor@joindaquest.io",
    username: "liamoconnor",
    password: "Testpass123@",
    referralCode: "LIAM2",
    role: "kol",
    referredBy: "None",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+ngozi-eze@joindaquest.io",
    username: "ngozieze",
    password: "Testpass123@",
    referralCode: "NGOZI3",
    role: "regular",
    referredBy: "amakaobi",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+tunde-balogun@joindaquest.io",
    username: "tundebalogun",
    password: "Testpass123@",
    referralCode: "TUNDE4",
    role: "regular",
    referredBy: "amakaobi",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+sofia-mensah@joindaquest.io",
    username: "sofiamensah",
    password: "Testpass123@",
    referralCode: "SOFIA5",
    role: "regular",
    referredBy: "amakaobi",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+carlos-mendes@joindaquest.io",
    username: "carlosmendes",
    password: "Testpass123@",
    referralCode: "CARLOS6",
    role: "regular",
    referredBy: "liamoconnor",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
  {
    email: "dev+aisha-khan@joindaquest.io",
    username: "aishakhan",
    password: "Testpass123@",
    referralCode: "AISHA7",
    role: "regular",
    referredBy: "liamoconnor",
    loginUrl: "/",
    dashboardUrl: "/dashboard",
  },
];
